source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'faker'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pry'
gem 'puma'
gem 'rails', '4.2.3'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'will_paginate'
